all:
  children:
    web:
      hosts:
        web01:
          ansible_host: 89.169.145.64
    syslog:
      hosts:
        syslog01:
          ansible_host: 51.250.43.183

  vars:
    ansible_user: mosty
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
