---
- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
  when: not ansible_check_mode

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  when: not ansible_check_mode

- name: Restart web stack
  community.docker.docker_compose_v2:
    project_src: "{{ project_dir }}/deploy"
    state: restarted
  when: not ansible_check_mode
